# Generated by Django 5.0.6 on 2024-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='title!@#', max_length=100),
            preserve_default=False,
        ),
    ]
